[workspace]
resolver = "2"
members = [
    "api",
    "api/common",
    "api/quic",
    "api/tcp",
    "api/wasi",
    "common",
    "modules/bench/common",
    "modules/bench/server",
    "pallet",
    "runtime",
]
default-members = ["runtime"]
